language: python

env:
  - TOX_ENV=py34
  - TOX_ENV=flake8

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py34' ]; then pip install coveralls; coveralls; fi"

notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
